export const Appetizers = [
    {
        id: 1,
        img: "https://media.istockphoto.com/id/1463672874/photo/bruschetta-breakfast-mozzarella-cheese-bread-pesto-sauce-and-tomatoes-on-wooden-table.jpg?b=1&s=612x612&w=0&k=20&c=U-U6HPRkdCKqkFpEbABQQHbwRQKGOa-GrQ_tmCQnLtQ=",
        name: "Bruschetta",
        desc: "Grilled bread topped with fresh tomatoes, garlic, basil, and olive oil.",
    },
    {
        id: 2,
        img: "https://media.istockphoto.com/id/1057566866/photo/creamy-crab-and-shrimp-stuffed-mini-portobello-mushroom-caps.jpg?b=1&s=612x612&w=0&k=20&c=EWJHiYpHnSRiu7XfqDSs3ED4TrCyZHji1lkgzAvLFo4=",
        name: "Stuffed Mushrooms",
        desc: "Mushrooms filled with a savory cheese and herb stuffing.",
    },
    {
        id: 3,
        img: "https://media.istockphoto.com/id/1577136375/photo/spicy-fried-chicken-rolls.jpg?b=1&s=612x612&w=0&k=20&c=9ghBO1fDtuoxV4Y8QehcCQH0L35Hjt1k1FmIZKnTkk8=",
        name: "Spring Rolls",
        desc: "Crispy rolls filled with vegetables and served with a sweet chili sauce.",
    },
    {
        id: 4,
        img: "https://media.istockphoto.com/id/1441714834/photo/fresh-garlic-bread-with-cheese-and-spices-on-the-wooden-table.jpg?b=1&s=612x612&w=0&k=20&c=Z3bHbiRgK-RO5HfeWwixJhmmMWkRcAvzj-Vf4RA3phQ=",
        name: "Garlic Bread",
        desc: "Slices of bread topped with garlic butter and baked until golden.",
    },
    {
        id: 5,
        img: "https://media.istockphoto.com/id/1264941753/photo/traditional-caprese-salad-top-view.jpg?b=1&s=612x612&w=0&k=20&c=9cTCFrv0ZBpO6kYw39_ngcDmqCdkxtxhRY1ZkyD383s=",
        name: "Caprese Salad",
        desc: "Fresh mozzarella, tomatoes, and basil drizzled with balsamic glaze.",
    },
    {
        id: 6,
        img: "https://media.istockphoto.com/id/1462713466/photo/fried-chicken-wings-with-potatoes-and-spices-homemade-fast-food-no-people.jpg?b=1&s=612x612&w=0&k=20&c=0ZAArDnOGqKzKNn4c2mMHHqyaJOz_YjN3Om4tVbLAec=",
        name: "Buffalo Wings",
        desc: "Spicy chicken wings served with blue cheese dip.",
    },
    {
        id: 7,
        img: "https://media.istockphoto.com/id/1270476552/photo/a-delicious-plate-of-deep-fried-calamari-squid-fried-to-perfection-cajun-style-served-with-a.jpg?b=1&s=612x612&w=0&k=20&c=uuq3xALvl3K1Xu1bK1EjMvMLWPvbq_R5Uu4gewX13Bo=",
        name: "Calamari",
        desc: "Fried squid rings served with marinara sauce.",
    },
    {
        id: 8,
        img: "https://media.istockphoto.com/id/1349067634/photo/artichoke-spinach-dip.jpg?b=1&s=612x612&w=0&k=20&c=xu-GBDZ1AdYaBJ3hryXk5XbXmfO9LNNfTRJ83RpPEmU=",
        name: "Spinach Artichoke Dip",
        desc: "Creamy dip served with toasted pita bread.",
    },
    {
        id: 9,
        img: "https://media.istockphoto.com/id/1263414282/photo/deviled-eggs.jpg?b=1&s=612x612&w=0&k=20&c=iriR-kLxn27uOk5R6jBOl8-L9pk9mETsH4hwuW7GO3E=",
        name: "Deviled Eggs",
        desc: "Hard-boiled eggs filled with a seasoned yolk mixture.",
    },
    {
        id: 10,
        img: "https://media.istockphoto.com/id/1267682119/photo/shrimps.jpg?b=1&s=612x612&w=0&k=20&c=uKcAH2EmjNCis82_5ORp8VypEXuXk8jLNAW9juAb_dA=",
        name: "Shrimp Cocktail",
        desc: "Chilled shrimp served with cocktail sauce.",
    },
    {
        id: 11,
        img: "https://media.istockphoto.com/id/1463117086/photo/shrimp-nachos-with-jalapenos.jpg?b=1&s=612x612&w=0&k=20&c=Js7YUh9rBgpqf0mx6-_IdzttK8nkMgxaeh5JveSdfEA=",
        name: "Nachos",
        desc: "Tortilla chips topped with cheese, jalapenos, sour cream, and guacamole.",
    },
    {
        id: 12,
        img: "https://media.istockphoto.com/id/1451088545/photo/purified-water-pouring-in-drinking-glass-on-rock-at-forest.jpg?b=1&s=612x612&w=0&k=20&c=nxTdmv9Z64dMlXINbywXG1ADhecNBvK5QEfh-wEJV9k=",
        name: "Mini Quiches",
        desc: "Bite-sized quiches filled with spinach and cheese.",
    },
    {
        id: 13,
        img: "https://media.istockphoto.com/id/1135334934/photo/loaded-potato-skins.jpg?b=1&s=612x612&w=0&k=20&c=5yax-bsVOB0dRRT5sPNIbZpz3y9Xk6i2CuH_7r1JC3Y=",
        name: "Potato Skins",
        desc: "Potato halves topped with cheese, bacon, and sour cream.",
    },
    {
        id: 14,
        img: "https://media.istockphoto.com/id/1224986971/photo/women-eating-fresh-mediterranean-platter-on-table.jpg?b=1&s=612x612&w=0&k=20&c=oDypgdP-2JuEKg9y1Begb69rvtMN4VfyKob2ueG2UOk=",
        name: "Hummus Platter",
        desc: "Served with pita bread, carrots, and celery sticks.",
    },
    {
        id: 15,
        img: "https://media.istockphoto.com/id/2070994097/photo/bowl-of-fried-brussel-sprouts-with-balsamic-vinegar-glaze.jpg?b=1&s=612x612&w=0&k=20&c=vuYMKJR42Tr3JqDN4sefgjk_IjVaFSRqh_RoHR7k8_I=",
        name: "Crispy Brussels Sprouts",
        desc: "Fried Brussels sprouts tossed with balsamic glaze.",
    },
    {
        id: 16,
        img: "https://media.istockphoto.com/id/475045278/photo/concept-of-italian-food.jpg?b=1&s=612x612&w=0&k=20&c=GQE9Oj2PMnlTrKT4ByXiRfDTa0XULBmQC5CtvCfutlI=",
        name: "Prosciutto and Melon",
        desc: "Slices of cantaloupe wrapped in prosciutto.",
    },
    {
        id: 17,
        img: "https://media.istockphoto.com/id/535317767/photo/baked-camembert-cheese.jpg?b=1&s=612x612&w=0&k=20&c=heAh8xlOoSCleRX-JjeXcD_jNpPcZ5jCM4WYUBXfjZQ=",
        name: "Baked Brie",
        desc: "Brie cheese baked with honey and served with crackers.",
    },
    {
        id: 18,
        img: "https://media.istockphoto.com/id/1355094124/photo/jalapeno-poppers-with-sour-cream.jpg?b=1&s=612x612&w=0&k=20&c=v3Pg96Y-wthf9T5pMfng_I87wuwx-W8Q8jRJbmurQ2A=",
        name: "Stuffed Jalapenos",
        desc: "Jalapeno peppers filled with cream cheese and wrapped in bacon.",
    },
    {
        id: 19,
        img: "https://media.istockphoto.com/id/1475059886/photo/pasta-spaghetti-with-meat-ball-in-tomato-sauce-top-view.jpg?b=1&s=612x612&w=0&k=20&c=9VEuXMlOsLtnNMkTWKmEn5qGaXZsMfNyDCv0YiDutMo=",
        name: "Meatballs",
        desc: "Beef and pork meatballs in marinara sauce.",
    },
    {
        id: 20,
        img: "https://media.istockphoto.com/id/1480666808/photo/cheese-plate.jpg?b=1&s=612x612&w=0&k=20&c=txHyYSY8VABOMCwD33rCLthCvsXUc-dT2Gu_ft_uNwU=",
        name: "Cheese Plate",
        desc: "Selection of cheeses served with fruit and nuts.",
    }
];

export const MainCourses = [
    {
        id: 1,
        img: "https://media.istockphoto.com/id/587207508/photo/sliced-grilled-steak-ribeye-with-herb-butter.jpg?b=1&s=612x612&w=0&k=20&c=m1SDeN7b0oLO3yCOV9KWdWCi2IuZB7nhrYow0p8KrKA=",
        name: "Grilled Ribeye Steak",
        desc: "Served with mashed potatoes and steamed vegetables.",
    },
    {
        id: 2,
        img: "https://media.istockphoto.com/id/154920482/photo/chicken-fettuccine-alfredo.jpg?b=1&s=612x612&w=0&k=20&c=jKIl-aJZHnUb3wolZtyJhEQ5X3nDWVz76tPwy3Qr1Gk=",
        name: "Chicken Alfredo",
        desc: "Grilled chicken breast over fettuccine pasta with creamy Alfredo sauce.",
    },
    {
        id: 3,
        img: "https://media.istockphoto.com/id/175028181/photo/fillet-of-salmon-with-vegetable.jpg?b=1&s=612x612&w=0&k=20&c=UQY4GBcW3axLDF4MxosQZApXL70f9y6mYLxLe5hyCl8=",
        name: "Salmon Fillet",
        desc: "Pan-seared salmon with a lemon butter sauce, served with rice and asparagus.",
    },
    {
        id: 4,
        img: "https://media.istockphoto.com/id/1207271995/photo/stir-frying-and-sauteing-a-variety-of-fresh-colorful-market-vegetables-in-a-hot-steaming-wok.jpg?b=1&s=612x612&w=0&k=20&c=82Hvr4hXkop4DHYhrSZSBPyIfcaNrKR3FFVeLAx7RPc=",
        name: "Vegetable Stir-Fry",
        desc: "Mixed vegetables sautéed with soy sauce and served over rice.",
    },
    {
        id: 5,
        img: "https://media.istockphoto.com/id/1191425335/photo/american-food-concept-grilled-pork-ribs-with-grilled-sauce-with-smoke-spices-and-rosemary.jpg?s=612x612&w=0&k=20&c=TXvrzSQ7JndB40X8BzNyInU0e78p5pdg0qFxsxZ5e_8=",
        name: "BBQ Ribs",
        desc: "Slow-cooked ribs glazed with barbecue sauce, served with coleslaw.",
    },
    {
        id: 6,
        img: "https://media.istockphoto.com/id/1429067111/photo/spaghetti-bolognese-top-view-close-up-no-people-homemade.jpg?b=1&s=612x612&w=0&k=20&c=8Ge6qSYRkYhsYwnegtC_Gr9D8dswD0xlb9OSQxB3qAg=",
        name: "Spaghetti Bolognese",
        desc: "Spaghetti topped with a rich meat sauce.",
    },
    {
        id: 7,
        img: "https://media.istockphoto.com/id/1307796427/photo/lamb-chops-with-roasted-root-vegetables.jpg?s=612x612&w=0&k=20&c=f98k5t0lOlHd-k4jlJxyH_n0bidL0BJyL1HkfVcAFPM=",
        name: "Lamb Chops",
        desc: "Grilled lamb chops served with rosemary and garlic sauce.",
    },
    {
        id: 8,
        img: "https://media.istockphoto.com/id/503203991/photo/homemade-italian-chicken-parmesan.jpg?b=1&s=612x612&w=0&k=20&c=12gczj_ltJTCTb_Brjzks8Dli_WjMbKUgPFZIoRTjdo=",
        name: "Chicken Parmesan",
        desc: "Breaded chicken breast topped with marinara sauce and melted mozzarella.",
    },
    {
        id: 9,
        img: "https://media.istockphoto.com/id/1328568894/photo/pork-tenderloin-medallions-in-a-creamy-mushroom-sauce.jpg?b=1&s=612x612&w=0&k=20&c=Me_XaJWgE7b3YIEmfCU7xwajOJQitGEjF4vgGz0SIvM=",
        name: "Beef Stroganoff",
        desc: "Tender beef strips in a creamy mushroom sauce, served over egg noodles.",
    },
    {
        id: 10,
        img: "https://media.istockphoto.com/id/1473145303/photo/seafood-paella-served-in-a-cast-iron-pan.jpg?b=1&s=612x612&w=0&k=20&c=nibaYzYNgV_g-ob0lo-0c386rqfCK6iuFqlZEyKmI-4=",
        name: "Seafood Paella",
        desc: "A Spanish dish of rice with seafood, saffron, and vegetables.",
    },
    {
        id: 11,
        img: "https://media.istockphoto.com/id/1303741768/photo/italian-lasagna-with-tomato-sauce-and-cheese-served-with-tomatoes-and-spinach-light-concrete.jpg?b=1&s=612x612&w=0&k=20&c=qfnIczbdemWvxb3QJ8fy0VsqubxP1_IGZB7ar_1vF_4=",
        name: "Vegetarian Lasagna",
        desc: "Layers of pasta, ricotta, spinach, and marinara sauce baked to perfection.",
    },
    {
        id: 12,
        img: "https://media.istockphoto.com/id/185009280/photo/red-bowl-of-delicious-chicken-teriyaki.jpg?b=1&s=612x612&w=0&k=20&c=hhlgazDVpx07Aw1PlxPRMR3uRuC8X4GE1mmoMY3D-C4=",
        name: "Teriyaki Chicken",
        desc: "Grilled chicken glazed with teriyaki sauce, served with steamed rice and vegetables.",
    },
    {
        id: 13,
        img: "https://media.istockphoto.com/id/179708004/photo/beef-barbacoa-tacos.jpg?b=1&s=612x612&w=0&k=20&c=BlGVl6o_uFbwGo2fy8526ZFGaCMTdLslbc3niv35Mrc=",
        name: "Beef Tacos",
        desc: "Seasoned beef in soft tortillas, topped with lettuce, cheese, and salsa.",
    },
    {
        id: 14,
        img: "https://media.istockphoto.com/id/1315023820/photo/cheesy-spinach-stuffed-pork-chops.jpg?b=1&s=612x612&w=0&k=20&c=IrkXEn3cAoQW29j0DQ0NxvlHKqqwvJk0VR3zj_ixo_E=",
        name: "Pork Chops",
        desc: "Grilled pork chops with apple sauce, served with roasted potatoes.",
    },
    {
        id: 15,
        img: "https://media.istockphoto.com/id/1218905269/photo/healthy-vegan-mushroom-risotto.jpg?b=1&s=612x612&w=0&k=20&c=amh-r5IYq3Ur_EjP8GTAPJJ_j5O3PJk0-n3eLFI0r_Q=",
        name: "Mushroom Risotto",
        desc: "Creamy risotto with wild mushrooms and Parmesan cheese.",
    },
    {
        id: 16,
        img: "https://media.istockphoto.com/id/1493534069/photo/traditional-fish-and-chips-takeout.jpg?b=1&s=612x612&w=0&k=20&c=UM3C4z5y5vxo3hqIjaAFsxHGGA43r-o8TJ-L4h_pQO8=",
        name: "Fish and Chips",
        desc: "Crispy fried fish served with French fries and tartar sauce.",
    },
    {
        id: 17,
        img: "https://media.istockphoto.com/id/1168662503/photo/tradicional-parmigiana-di-melanzane-baked-eggplant-italy-sicily-cousine-baked-eggplant-with.jpg?b=1&s=612x612&w=0&k=20&c=hLovkOwU3ah9ihNfEuJ2ib55FeVneurTB9p9Ak_I-_U=",
        name: "Eggplant Parmesan",
        desc: "Breaded eggplant slices baked with marinara sauce and mozzarella.",
    },
    {
        id: 18,
        img: "https://media.istockphoto.com/id/1312459972/photo/homemade-indian-butter-chicken-with-rice.jpg?b=1&s=612x612&w=0&k=20&c=jZM76eGVmsjIsff49lddw6HqT74Pwks3x5noAXJWOko=",
        name: "Chicken Curry",
        desc: "Spicy chicken curry served with basmati rice and naan bread.",
    },
    {
        id: 19,
        img: "https://media.istockphoto.com/id/1060547602/photo/pasta-ziti-with-bolognese-sauce-and-cheese-close-up-horizontal-top-view-rustic-style.jpg?b=1&s=612x612&w=0&k=20&c=BgSjkqik8beWIOWFxK6z_vITa98kkryiy_JwIivwryo=",
        name: "Baked Ziti",
        desc: "Pasta baked with marinara sauce, ricotta, and mozzarella cheese.",
    },
    {
        id: 20,
        img: "https://img.freepik.com/free-photo/chicken-wrap-served-with-fries-salad_140725-4121.jpg?size=626&ext=jpg&ga=GA1.1.329726886.1716801509&semt=sph",
        name: "Fajitas",
        desc: "Grilled beef or chicken with bell peppers and onions, served with tortillas.",
    }
];

export const Desserts = [
    {
        id: 1,
        img: "https://media.istockphoto.com/id/1641085425/photo/pumpkin-cheesecake-with-fall-spices-topped-with-whipped-cream.jpg?b=1&s=612x612&w=0&k=20&c=Ng4viijTI0XShBLYvwIseCbV2Q3faNWxeradRwGiyK4=",
        name: "Cheesecake",
        desc: "Creamy cheesecake with a graham cracker crust.",
    },
    {
        id: 2,
        img: "https://media.istockphoto.com/id/180811737/photo/chocolate-mousse.jpg?b=1&s=612x612&w=0&k=20&c=pQc4NXY8jnP6Vv24iyTZKqkq9C8-G6mw26-JjaEnxMk=",
        name: "Chocolate Mousse",
        desc: "Rich and fluffy chocolate mousse topped with whipped cream.",
    },
    {
        id: 3,
        img: "https://media.istockphoto.com/id/1423422264/photo/festive-christmas-dessert-tiramisu-sponge-cake-in-bright-rustic-kitchen-with-golden-christmas.jpg?b=1&s=612x612&w=0&k=20&c=qk0ZuuxovuL1vkSo3gZvnWWQf-q_MQcgOn63WDVRNjE=",
        name: "Tiramisu",
        desc: "Classic Italian dessert made with layers of coffee-soaked ladyfingers and mascarpone cheese.",
    },
    {
        id: 4,
        img: "https://media.istockphoto.com/id/1345857656/photo/assortment-of-homemade-fall-pies-table-scene-on-dark-wood.jpg?s=612x612&w=0&k=20&c=QQLOLFmsVbBVa4tD_3hMse-zF3dbXPZkCiFVAFYw0nU=",
        name: "Apple Pie",
        desc: "Warm apple pie served with a scoop of vanilla ice cream.",
    },
    {
        id: 5,
        img: "https://media.istockphoto.com/id/1255426185/photo/delicious-chocolate-zucchini-brownies.jpg?b=1&s=612x612&w=0&k=20&c=h89bYq9xS7-Szp2IoOqYn1kgDo8_SdocNWJZjZbGiWg=",
        name: "Brownies",
        desc: "Fudgy chocolate brownies with a crispy crust.",
    },
    {
        id: 6,
        img: "https://media.istockphoto.com/id/644145266/photo/chocolate-ice-cream-sundae-with-sauce.jpg?s=612x612&w=0&k=20&c=qgIVGNfzll7cFy7ar9gSxTKb8mLaQFZjiJt-n1ZEMnU=",
        name: "Ice Cream Sundae",
        desc: "Vanilla ice cream topped with hot fudge, whipped cream, and a cherry.",
    },
    {
        id: 7,
        img: "https://media.istockphoto.com/id/1553363396/photo/mango-mousse-with-fresh-mango-and-mango-puree.jpg?b=1&s=612x612&w=0&k=20&c=UkZ-rnbfVdO4LZ1h-GcjudxO9t6LmPp-IS5fw1I2W24=",
        name: "Panna Cotta",
        desc: "Silky smooth panna cotta served with a berry compote.",
    },
    {
        id: 8,
        img: "https://media.istockphoto.com/id/1399715510/photo/traditional-french-vanilla-cream-dessert-with-caramelized-sugar.jpg?b=1&s=612x612&w=0&k=20&c=S967AfBODSwS0q5-mn1rNq2Fc_RT6BvP6xrqS0BmJhI=",
        name: "Creme Brulee",
        desc: "Rich custard topped with a layer of caramelized sugar.",
    },
    {
        id: 9,
        img: "https://media.istockphoto.com/id/1473541326/photo/colorful-decorated-easter-table-with-easter-eggs-flowers-and-carrot-easter-cake.jpg?b=1&s=612x612&w=0&k=20&c=uHBx8vrH6QP3MR4KwqnO_ef2XHknwD2GrXE80e7gXwI=",
        name: "Carrot Cake",
        desc: "Moist carrot cake with cream cheese frosting.",
    },
    {
        id: 10,
        img: "https://media.istockphoto.com/id/610958912/photo/molten-lava-chocolate-cake-with-dolce-de-leche.jpg?b=1&s=612x612&w=0&k=20&c=DQ6ssKRDZLimRsvEj04Mbz4NAE4rRaLBYsHfm-zHUwA=",
        name: "Molten Lava Cake",
        desc: "Warm chocolate cake with a gooey, melted center.",
    },
    {
        id: 11,
        img: "https://media.istockphoto.com/id/155908717/photo/lime-pie.jpg?b=1&s=612x612&w=0&k=20&c=tu5-JhcPXmfo0YPpIMdNL8wK9m2JC0HDpz0dzrAHo3Y=",
        name: "Lemon Tart",
        desc: "Tangy lemon tart with a buttery crust.",
    },
    {
        id: 12,
        img: "https://media.istockphoto.com/id/518273814/photo/delicious-berry-pavlova-cake-with-strawberries-and-raspberries.jpg?b=1&s=612x612&w=0&k=20&c=X2LtclS31YFMmrNn7vxdPFJtnz5c5MhEDj0ZdD6sLqQ=",
        name: "Pavlova",
        desc: "Crispy meringue shell topped with whipped cream and fresh fruit.",
    },
    {
        id: 13,
        img: "https://media.istockphoto.com/id/1560408457/photo/healthy-fruit-salad-in-a-grey-bowl-made-with-avocado-strawberry-raspberry-orange-blackberry.jpg?b=1&s=612x612&w=0&k=20&c=Mk8U_n1alyvC6f-O8ii5JCLvnMxnD-kRBDI6AD14bGo=",
        name: "Fruit Salad",
        desc: "A mix of fresh seasonal fruits.",
    },
    {
        id: 14,
        img: "https://media.istockphoto.com/id/155598375/photo/dessert-chocolate-cake.jpg?b=1&s=612x612&w=0&k=20&c=tBdGktNXwB3chgUMQePPTrywhhLnvQ_WidTw53kUOwc=",
        name: "Chocolate Cake",
        desc: "Rich chocolate cake with chocolate frosting.",
    },
    {
        id: 15,
        img: "https://media.istockphoto.com/id/168490861/photo/banana-split.jpg?b=1&s=612x612&w=0&k=20&c=RpAGZYIkChM_SToMcxQeqXYKwEyBJkwpV2mkrGp8r2s=",
        name: "Banana Split",
        desc: "Banana split in half, topped with ice cream, hot fudge, whipped cream, and nuts.",
    },
    {
        id: 16,
        img: "https://media.istockphoto.com/id/183340818/photo/closeup-picture-of-profiteroles-bathing-in-chocolate.jpg?b=1&s=612x612&w=0&k=20&c=kGbefKfscg6ADo-pRMfGA9YBCZw3BYaEbDvN1wDnMgU=",
        name: "Profiteroles",
        desc: "Choux pastry filled with cream and topped with chocolate sauce.",
    },
    {
        id: 17,
        img: "https://media.istockphoto.com/id/1473312639/photo/traditional-turkish-ramadan-table.jpg?b=1&s=612x612&w=0&k=20&c=k4Ju_B2ejmcBaEXBYdATfeWzwrzOIsDC9kv6OIfBoM4=",
        name: "Baklava",
        desc: "Layers of phyllo pastry filled with nuts and honey syrup.",
    },
    {
        id: 18,
        img: "https://media.istockphoto.com/id/1138250670/photo/homemade-pastry-eclair.jpg?b=1&s=612x612&w=0&k=20&c=NZSvHmn2G49RprIqV53iiYyp299vRfQBPisaR5-LlhI=",
        name: "Eclairs",
        desc: "Choux pastry filled with cream and topped with chocolate glaze.",
    },
    {
        id: 19,
        img: "https://media.istockphoto.com/id/493068221/photo/italian-cannolis.jpg?b=1&s=612x612&w=0&k=20&c=W14V4XabNKu_V1sKCSny-mXhecfQkQUskVxhGoVhp84=",
        name: "Cannoli",
        desc: "Crispy pastry shells filled with sweetened ricotta cheese.",
    },

];

export const Beverages = [
    {
        id: 1,
        img: "https://media.istockphoto.com/id/1467199060/photo/cup-of-coffee-with-smoke-and-coffee-beans-on-old-wooden-background.jpg?b=1&s=612x612&w=0&k=20&c=pYVOIV8N70JYqIbnGSJdtGftKYleSMkWg4r_bnVef_8=",
        name: "Coffee",
        desc: "Freshly brewed coffee.",
    },
    {
        id: 2,
        img: "https://media.istockphoto.com/id/1441569995/photo/close-up-shot-of-a-poring-milk-in-a-hot-tea.jpg?b=1&s=612x612&w=0&k=20&c=W6D9AJjOilq7Nz6f_brv-styidmgtkeAdmhD1ERsmIg=",
        name: "Tea",
        desc: "Selection of black, green, and herbal teas.",
    },
    {
        id: 3,
        img: "https://media.istockphoto.com/id/155376375/photo/fruit-juice.jpg?b=1&s=612x612&w=0&k=20&c=p-dtIRRYBi4WiZvDjejs2I4QmeTzM8Tk28_1nMd_L_4=",
        name: "Fresh Juice",
        desc: "Orange, apple, and grapefruit juice.",
    },
    {
        id: 4,
        img: "https://media.istockphoto.com/id/1415615249/photo/fruit-smoothie-ingredients-in-a-blender.jpg?b=1&s=612x612&w=0&k=20&c=GCx6tZ-62ItMGa-OY_gc2ArjaTPCvLXz6Lj3ID0_oBI=",
        name: "Smoothies",
        desc: "Blend of fresh fruits and yogurt.",
    },
    {
        id: 5,
        img: "https://media.istockphoto.com/id/1485723757/photo/peanut-butter-smoothie.jpg?b=1&s=612x612&w=0&k=20&c=fAzLRYP3pDY01p7jgmg7F5kMzlqtvhbo3pBNu2UeCCo=",
        name: "Milkshakes",
        desc: "Vanilla, chocolate, and strawberry milkshakes.",
    },
    {
        id: 6,
        img: "https://media.istockphoto.com/id/1062831310/photo/pour-soft-drink-in-glass-with-ice-splash-on-dark-background.jpg?s=612x612&w=0&k=20&c=XlLTcFQ0FqcTWRa9QniHgpjlkdFrOJGJFGm5jg_TAAw=",
        name: "Soda",
        desc: "Variety of carbonated soft drinks.",
    },
    {
        id: 7,
        img: "https://images.pexels.com/photos/416528/pexels-photo-416528.jpeg?auto=compress&cs=tinysrgb&w=600",
        name: "Mineral Water",
        desc: "Sparkling and still mineral water.",
    },
    {
        id: 8,
        img: "https://media.istockphoto.com/id/1364461834/photo/freshly-made-lemonade.jpg?b=1&s=612x612&w=0&k=20&c=6HyaOOMXg9xDFrWivyeD_sTrfr-TPRmrrzpY1dYbWEA=",
        name: "Lemonade",
        desc: "Refreshing homemade lemonade.",
    },
    {
        id: 9,
        img: "https://media.istockphoto.com/id/698163522/photo/ice-tea-with-lemon-and-mint-in-a-jar.jpg?b=1&s=612x612&w=0&k=20&c=_2-ewUIF7MEIGzbW5Dgy3z7nNtzA5VEhNzKBU5mtpqs=",
        name: "Iced Tea",
        desc: "Chilled iced tea with lemon.",
    },
    {
        id: 10,
        img: "https://media.istockphoto.com/id/1458068034/photo/chocolate-ingredients.jpg?b=1&s=612x612&w=0&k=20&c=zYw7UYzLIfh2UH82Ur5D9GvNhmZr_gPNZaQLmywNCwM=",
        name: "Hot Chocolate",
        desc: "Rich and creamy hot chocolate.",
    },
    {
        id: 11,
        img: "https://media.istockphoto.com/id/1222552753/photo/green-detox-juice.jpg?b=1&s=612x612&w=0&k=20&c=TY2nWjQN-FGUwk6F1hs0lMQvHUm9p-EhvJn0i1CUZrU=",
        name: "Vegetable Juice",
        desc: "Healthy blend of fresh vegetables.",
    },
    {
        id: 12,
        img: "https://media.istockphoto.com/id/1019323316/photo/mint-mojito-cocktail.jpg?b=1&s=612x612&w=0&k=20&c=OdtolyJatQuzBL3b5g-fBEQ1GbCiYICWT9SfM62AdtI=",
        name: "Mocktails",
        desc: "Non-alcoholic cocktails.",
    },
    {
        id: 13,
        img: "https://media.istockphoto.com/id/153767661/photo/energy-drink-from-the-top.jpg?s=612x612&w=0&k=20&c=f6DjY8dfEFYuav-DYXWhbmba4_N5WT92hp7Ke-6mdtk=",
        name: "Energy Drinks",
        desc: "Variety of energy-boosting drinks.",
    },
    {
        id: 14,
        img: "https://media.istockphoto.com/id/535489242/photo/pouring-milk-in-the-glass-on-the-background-of-nature.jpg?s=612x612&w=0&k=20&c=bqBubtMFs_kv9z0OZVLunl3NFTb_XAVKiw8v1hO1T80=",
        name: "Milk",
        desc: "Whole, skim, and almond milk.",
    },
    {
        id: 15,
        img: "https://media.istockphoto.com/id/174757029/photo/coconut-water-and-nut.jpg?b=1&s=612x612&w=0&k=20&c=ut4WcH_T78uor4I_xdhhX2Y0p81XHHsLRx1abdujlHE=",
        name: "Coconut Water",
        desc: "Fresh coconut water.",
    },
    {
        id: 16,
        img: "https://media.istockphoto.com/id/1396531657/photo/close-up-of-woman-making-kombucha-at-home.jpg?b=1&s=612x612&w=0&k=20&c=3OL8sQq_57LfRUsX6w07fUDqi7AkpLW8IAcFchbBSdM=",
        name: "Kombucha",
        desc: "Fermented tea drink.",
    },

];
export const SpecialtyItems = [
    {
        id: 1,
        img: "https://media.istockphoto.com/id/1500141300/photo/bbq-classic-burger-against-fiery-flames-vibrant-food-black-background.jpg?b=1&s=612x612&w=0&k=20&c=rW_3gOkPeGact_NsOB_GAnSUo71gGPPJsATOJ8ZtrlE=",
        name: "Gourmet Burger",
        desc: "A juicy burger with premium toppings such as truffle aioli and aged cheddar.",
    },
    {
        id: 2,
        img: "https://media.istockphoto.com/id/509533212/photo/homemade-new-england-lobster-roll.jpg?s=612x612&w=0&k=20&c=wUC2J86Leyu3KFPLTwBjeMmRzfaSGHH-x8k_XPwFaVc=",
        name: "Lobster Roll",
        desc: "A traditional New England lobster roll served with a side of coleslaw.",
    },
    {
        id: 3,
        img: "https://media.istockphoto.com/id/169975046/photo/raw-marbled-new-york-steaks.jpg?b=1&s=612x612&w=0&k=20&c=_c-A6bKBX1y-sc9A_HZ7n9XJXtwoURGoUxLD49tsQSY=",
        name: "Wagyu Beef Steak",
        desc: "Premium wagyu beef steak cooked to perfection.",
    },
    {
        id: 4,
        img: "https://media.istockphoto.com/id/1556537640/photo/hand-holding-sushi-with-chopsticks.jpg?b=1&s=612x612&w=0&k=20&c=Xm2lYBpyDvo60SGDDLO6VTCaXxLIclifLWDsyO8w3_c=",
        name: "Sushi Platter",
        desc: "A variety of fresh sushi and sashimi, beautifully presented.",
    },
    {
        id: 5,
        img: "https://media.istockphoto.com/id/1972709887/photo/duck-confit-with-puy-lentils-and-spinach.jpg?b=1&s=612x612&w=0&k=20&c=KAiLvCoyKj9Tlv_nYz6p0MaCGrqtmn3iQSKk0NPC1mI=",
        name: "Duck Confit",
        desc: "Slow-cooked duck leg with crispy skin, served with a side of roasted vegetables.",
    },
    {
        id: 6,
        img: "https://media.istockphoto.com/id/1791072788/photo/top-view-of-truffle-fettuccine-with-mushrooms-long-egg-pasta-italian-first-course-made-with.jpg?b=1&s=612x612&w=0&k=20&c=060-QlPbiz7zSoB5_HZ9G0C76flcUzAD-XXKjdbloi8=",
        name: "Truffle Pasta",
        desc: "Homemade pasta with a creamy truffle sauce and shaved truffles.",
    },
    {
        id: 7,
        img: "https://media.istockphoto.com/id/1423438856/photo/seared-foie-gras.jpg?b=1&s=612x612&w=0&k=20&c=F-04fltKU-cxth0kRRJStKbwQr5ZOBBAnC9kVDLMy80=",
        name: "Foie Gras",
        desc: "Delicate and rich foie gras served with a fruit compote.",
    },
    {
        id: 8,
        img: "https://media.istockphoto.com/id/1488695941/photo/directly-above-photo-of-delicious-tonkotsu-ramen-in-a-ceramic-bowl.jpg?b=1&s=612x612&w=0&k=20&c=bj0YdKGv24NA31-nRLViwi2Pb-2iWS9rIt7HNA6i-K8=",
        name: "Ramen",
        desc: "Authentic Japanese ramen with a flavorful broth and various toppings.",
    },
    {
        id: 9,
        img: "https://media.istockphoto.com/id/1473145303/photo/seafood-paella-served-in-a-cast-iron-pan.jpg?b=1&s=612x612&w=0&k=20&c=nibaYzYNgV_g-ob0lo-0c386rqfCK6iuFqlZEyKmI-4=",
        name: "Paella",
        desc: "Traditional Spanish paella with seafood and saffron rice.",
    },
    {
        id: 10,
        img: "https://media.istockphoto.com/id/167311970/photo/braised-lamb-chops.jpg?b=1&s=612x612&w=0&k=20&c=FnrqT9bTlTp0PFdq9EFPyDYweK_-fYemjPeQ8YdR67Y=",
        name: "Rack of Lamb",
        desc: "Herb-crusted rack of lamb served with a red wine reduction.",
    },
    {
        id: 11,
        img: "https://media.istockphoto.com/id/1387137406/photo/turkey-wellington-food.jpg?b=1&s=612x612&w=0&k=20&c=6AQLX0lE_kQHa2Y8RnhpgMR5LqYutzjuo9YcjIZnGoM=",
        name: "Beef Wellington",
        desc: "Tender beef filet wrapped in puff pastry and baked to perfection.",
    },
    {
        id: 12,
        img: "https://media.istockphoto.com/id/1252463614/photo/octopus-ceviche-with-fish-onion-chili-pepper-and-lemon.jpg?b=1&s=612x612&w=0&k=20&c=UzcXSxEQZsTe4doceMa9Rq29CJVQzC_SNWu6Ie_V6W8=",
        name: "Octopus",
        desc: "Grilled octopus served with a side of potatoes and smoked paprika.",
    },
    {
        id: 13,
        img: "https://media.istockphoto.com/id/1251551904/photo/beef-tartare-with-quail-egg-and-spices.jpg?b=1&s=612x612&w=0&k=20&c=pW2yiiuqO3KnL7vgeKCP19iX_1KWowwb2GQkEMtAWzg=",
        name: "Tartare",
        desc: "Fresh beef or tuna tartare served with crostini and garnishes.",
    },
    {
        id: 14,
        img: "https://media.istockphoto.com/id/1480666808/photo/cheese-plate.jpg?b=1&s=612x612&w=0&k=20&c=txHyYSY8VABOMCwD33rCLthCvsXUc-dT2Gu_ft_uNwU=",
        name: "Cheese Board",
        desc: "A selection of artisanal cheeses served with crackers and fruit.",
    },
    {
        id: 15,
        img: "https://media.istockphoto.com/id/1557558337/photo/cutting-of-peking-roast-duck-chinese-style-dishes-that-are-famous-in-thai-restaurants.jpg?b=1&s=612x612&w=0&k=20&c=RQeCz_MvQ5V4Y9_hcPegJ2EPjjQ3380Gzs4725MBKUA=",
        name: "Peking Duck",
        desc: "Crispy Peking duck served with pancakes and hoisin sauce.",
    },
    {
        id: 16,
        img: "https://media.istockphoto.com/id/1475375781/photo/risotto.jpg?b=1&s=612x612&w=0&k=20&c=I5TH3VRhpjbzLOMtgUTLxJnkRQtK9gjXTvtkneY6c0U=",
        name: "Risotto",
        desc: "Creamy risotto with wild mushrooms and parmesan.",
    },
    {
        id: 17,
        img: "https://media.istockphoto.com/id/1441261891/photo/food-photos-various-entrees-appetizers-deserts-etc.jpg?b=1&s=612x612&w=0&k=20&c=4m6ILSooWmKbOnTLJ-JXM85dxgkzhowGnCy0i5ZQ-E0=",
        name: "Tandoori Chicken",
        desc: "Marinated chicken cooked in a traditional tandoor oven.",
    },

];
